server:
  port: 8082
#jdbc
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB #限制文件上传大小

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    #配置实例id
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
