server:
  port: 8081
#jdbc
spring:
  application:
    name: item-service
  datasource:
#    url: jdbc:mysql://1.0.4.102:3306/demo_hei
    url: jdbc:mysql://1.0.4.102:3306/yun6
    username: root
    password: root

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    #配置实例id
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl